/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package webscraper;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

public class WebScraperTest {

    @Test
    void theCounterMethodIsWorkingAsExpected() {
        assertEquals(3, WebScraper.count("Jag skrev ett test som handlade om olika test. Men inte ett bromstest", "test"));
    }

    @Test
    void theCounterMethodIsNotCaseSensitive() {
        assertEquals(3, WebScraper.count("TEstIngTEstingTEST", "teSt"));
    }

    @Test 
    void theCrawlAndScrapeMethodReturnsTheExpectedResult() {
        WebScraper webScraper = new WebScraper();
        try {
            assertEquals(13, webScraper.crawlAndScrape("http://www.pmichaud.com/toast/", "flames", 1));
        } catch(Exception e) {
            e.getStackTrace();
        }
    }
    //The test crawls/scrapes the website pmichaud.com/toast that has not been modified since 1996 and expects the word flames will occur 13 times. 
}
